client_id = "b7103280b4167c2e9c882fcc49724092"
name = "paw-perks"
application_url = "https://pawperks-pawmart-prod-e7dze8h0e6ckg4bz.eastus2-01.azurewebsites.net"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = ["app/uninstalled"]

[[webhooks.subscriptions]]
uri = "/webhooks/app/scopes_update"
topics = ["app/scopes_update"]

[[webhooks.subscriptions]]
uri = "/webhooks/refunds/create"
topics = ["refunds/create"]

[[webhooks.subscriptions]]
uri = "/webhooks/orders/paid"
topics = ["orders/paid"]

[access_scopes]
scopes = "read_customers,read_orders,read_products,write_app_proxy,write_customers,write_discounts"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://pawperks-pawmart-prod-e7dze8h0e6ckg4bz.eastus2-01.azurewebsites.net/api/auth"
]

[app_proxy]
url = "https://pawperks-pawmart-prod-e7dze8h0e6ckg4bz.eastus2-01.azurewebsites.net/paw-perks"
prefix = "apps"
subpath = "paw-perks"
